server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost/devops-back
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update